# Generated by Django 4.2.3 on 2023-08-09 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Testimonial',
        ),
    ]
