# Generated by Django 4.2.3 on 2023-08-15 21:43

import django.core.validators
from django.db import migrations, models
import online_shop.web.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), online_shop.web.validators.validate_value_is_all_num]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, error_messages={'invalid': 'Invalid discount code.'}, unique=True),
        ),
    ]
