# Generated by Django 4.2.3 on 2023-07-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dmappuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmappuser',
            name='profile_image',
        ),
    ]
