# Generated by Django 4.2.3 on 2023-08-09 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_dmappuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmappuser',
            name='phone_number',
            field=models.CharField(error_messages={'max_length': 'Phone number must have 10 characters.', 'min_length': 'Phone number must have 10 characters.'}, max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
