# Generated by Django 4.2.3 on 2023-07-19 22:01

import django.core.validators
from django.db import migrations, models
import online_shop.products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('photo', models.ImageField(upload_to='product_photos/', validators=[online_shop.products.validators.validate_file_less_than_5mb])),
                ('description', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)])),
                ('price', models.FloatField(validators=[online_shop.products.validators.validate_value_is_greater_than_zero])),
            ],
        ),
    ]
