# Generated by Django 4.2.3 on 2023-07-31 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('delivery_type', models.CharField(choices=[('H', 'Delivery to the door'), ('O', 'Delivery to the office')], max_length=40)),
                ('delivery_company', models.CharField(choices=[('E', 'Econt'), ('S', 'Speedy')], max_length=10)),
                ('address', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10)])),
                ('is_verified', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
