# Generated by Django 4.2.3 on 2023-08-06 21:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_alter_orders_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
